
name: Github actions maven project


on: 
  push: 
    branches: [ master ]


jobs: 

  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: 1-Checkout main branch
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0 
    
    
      - name: 2-Set-up JDK version
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
       
       
      - name: 3-Have Github actions Build maven project
        run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging
        
  sonarCloudTrigger:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
        
      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: bin
          
      - name: 4-Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       
       
      - name: 5-Uploading Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: github-actions-artifact
          path: staging
   
