
name: Github actions maven project


on: 
  push: 
    branches: [ master ]


jobs: 

  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: 1-Checkout main branch
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0 
    
    
      - name: 2-Set-up JDK version
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
       
       
      - name: 3-Remove pom
        run: rm -f pom.xml 
         # mvn -B package --file pom.xml
         # mkdir staging && cp target/*.jar staging
         
      - name: 4-Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
          
      - name: 5-Build
        run: ant buildAll
          
      - name: 6-Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       
       
      - name: 7-Uploading Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: github-actions-artifact
          path: staging
   
