
name: Github actions maven project


on: 
  push: 
    branches: [ master ]


jobs: 

  build: 
    runs-on: ubuntu-latest
    
    steps: 
    - name: 1-Checkout main branch
      uses: actions/checkout@v2
    
    
    - name: 2-Set-up JDK version
      uses: actions/setup-java@v1
      with: 
        java-version: 1.8
       
       
    - name: 3-Have Github actions Build maven project
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging
        
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with: 
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
       
    - name: 4-Uploading Artifacts
      uses: actions/upload-artifact@v2
      with: 
         name: github-actions-artifact
         path: staging
   
